import type { Campaign } from './types';
import { media } from './media';
export const campaigns:Campaign[] = [
  {id:'afterglow',slug:'afterglow',title:'Afterglow',eyebrow:'A study in movement',category:'Fashion editorial',description:'When the light leaves, the feeling stays. A visual exploration of fabric, movement and the last light of day.',services:['Creative direction','Fashion shoots','Visual storytelling'],cover:media.fashion,gallery:[media.fashion,media.product],videoId:'afterglow-motion',accent:'#672B35',concept:true,
  story:[{title:'The brief',text:'Explore how a single feeling can become a visual language for fashion. This self-initiated concept uses AI-generated imagery to demonstrate an editorial direction; it is not commissioned client work.'},{title:'The idea',text:'Let the landscape become a second character. Oxblood fabric against sun-warmed stone creates tension between softness and structure.'},{title:'The execution',text:'A deliberately limited palette, strong silhouettes and generous negative space give every crop a point of view. A moving-image study extends the same direction into the feed.'},{title:'The experience',text:'One story, multiple frames: a campaign image, a portrait crop and a short motion study. Each piece feels connected without repeating the same composition.'}]},
  {id:'slow-hours',slug:'slow-hours',title:'The slow hours',eyebrow:'An invitation to stay',category:'Hospitality & lifestyle',description:'The warmth of a place, long before you arrive. An atmosphere-led concept shaped around the beauty of slowing down.',services:['Brand shoots','Content creation','Social direction'],cover:media.hospitality,gallery:[media.hospitality,media.fashion],videoId:'slow-hours-motion',accent:'#98633C',concept:true,
  story:[{title:'The brief',text:'Translate the feeling of a considered hospitality experience into social-first imagery. This is an independent concept using AI-generated visuals, not a commissioned campaign.'},{title:'The idea',text:'Make the small rituals the main event. Afternoon light, the first sip and the texture of linen tell a story before a word is spoken.'},{title:'The execution',text:'Warm color, tactile surfaces and unhurried framing guide this visual direction. The composition is designed to work as a full campaign still or an intimate vertical crop.'},{title:'The experience',text:'Content that makes space for the viewer. A gentle invitation to imagine being there, expressed through stills and a short motion study.'}]},
  {id:'objects-of-desire',slug:'objects-of-desire',title:'Objects of desire',eyebrow:'Ordinary, reimagined',category:'Product & brand',description:'A quiet object. A dramatic entrance. A study in making product imagery feel like a scene from a film.',services:['Brand shoots','Photography','Art direction'],cover:media.product,gallery:[media.product,media.hospitality],videoId:'objects-motion',accent:'#52212D',concept:true,
  story:[{title:'The brief',text:'Find the cinematic potential in a simple product silhouette. This is a self-initiated visual concept using an unbranded AI-generated object, not a real brand partnership.'},{title:'The idea',text:'Treat light as the storyteller. A sculptural bottle, a precise shadow and a deep burgundy stage create drama without visual clutter.'},{title:'The execution',text:'The product sits at the intersection of still life and film. Controlled contrast and a tactile set turn a functional object into the focal point of an imagined narrative.'},{title:'The experience',text:'A flexible creative direction for a hero image, an editorial detail and a moving product moment. The visual language stays recognizable across different formats.'}]},
];
